sudo: true
dist: xenial

language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        {%- for version in cookiecutter.supported_modern_python_versions.split() %}
        # CPython {{version}}
          {%- for type in ["local", "integ", "examples"] %}
        - python: {{version}}
          env: TOXENV=py{{version.replace(".", "")}}-{{type}}
          stage: Client Tests
          {%- endfor %}
        {%- endfor %}
        # Security
        - python: {{cookiecutter.default_python}}
          env: TOXENV=bandit
          stage: Static Checks
        # Linting
        - python: {{cookiecutter.default_python}}
          env: TOXENV=lint
          stage: Static Checks
        # MyPy
        - python: {{cookiecutter.default_python}}
          env: TOXENV=mypy
          stage: Static Checks

install: pip install tox
script: tox -- -vv
