# https://packaging.python.org/guides/supporting-windows-using-appveyor/

environment:

    matrix:
        # The only tests we perform on Windows are actual code tests.
        # All linting, static analysis, etc are only run on Linux.

        {%- for version in cookiecutter.supported_modern_python_versions.split() %}
        # Python {{version}}
            {%- for type in ["local", "integ", "examples"] %}
                {%- for runtime in ["", "-x64"] %}
        - PYTHON: "C:\\Python{{version.replace('.', '')}}{{runtime}}"
          TOXENV: "py{{version.replace('.', '')}}-{{type}}"
                {%- endfor %}
            {%- endfor %}
        {%- endfor %}

install:
    # Prepend newly installed Python to the PATH of this build
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    # Check the Python version to verify that the correct version was installed
    - "python --version"
    - "python -m pip install --upgrade setuptools wheel tox"

build: off

test_script:
    - "tox -- -vv"
