# This workflow runs local tests
name: local tests

on: [pull_request]

jobs:
  tests:
    runs-on: ${% raw %}{{ matrix.os }}{% endraw %}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          {%- for version in cookiecutter.supported_modern_python_versions.split() %}
          - {{version}}
          {%- endfor %}
          - 3.x
        architecture:
          - x64
          - x86
        category:
          - local
        # x86 builds are only meaningful for Windows
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: macos-latest
            architecture: x86
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${% raw %}{{ matrix.python }}{% endraw %}
          architecture: ${% raw %}{{ matrix.architecture }}{% endraw %}
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r ci-requirements.txt
      - name: run test
        env:
          TOXENV: ${% raw %}{{ matrix.category }}{% endraw %}
        run: tox -- -vv
