# This workflow applies repository settings once they land in master.
name: Apply repository settings

on:
  push:
    branches:
      - master

jobs:
  apply-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mattsb42/repo-manager@v1.0.0
        with:
          github-token: ${% raw %}{{ secrets.ADMIN_BOT_TOKEN }}{% endraw %}
          debug: true
