# This workflow automatically merges pull requests when they are ready.
name: automerge PRs

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  # Temporarily disable auto-merge to {{cookiecutter.development_branch}} until I have a solution for forks.
  #
  #  # Auto-approve anything to {{cookiecutter.development_branch}} as long as it meets the merge requirements
  #  automerge-to-{{cookiecutter.development_branch}}:
  #    if: github.base_ref == '{{cookiecutter.development_branch}}'
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: automerge
  #        uses: pascalgn/automerge-action@v0.8.1
  #        env:
  #          GITHUB_TOKEN: ${% raw %}{{ secrets.WRITE_TOKEN }}{% endraw %}
  #          # Do not merge if the "block merge" label is applied.
  #          MERGE_LABELS: "!block merge"
  #          # Always do a squash commit.
  #          MERGE_METHOD: squash
  #          # Use GitHub's default merge commit message.
  #          MERGE_COMMIT_MESSAGE: automatic
  # Only auto-approve PRs to master if they came from {{cookiecutter.development_branch}} in this fork
  automerge-to-master:
    if: github.head_ref == '{{cookiecutter.development_branch}}' && github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.8.1
        env:
          GITHUB_TOKEN: ${% raw %}{{ secrets.WRITE_BOT_TOKEN }}{% endraw %}
          # Do not merge if the "block merge" label is applied.
          MERGE_LABELS: "!block merge"
          # Always do a merge commit.
          # This is critical to keep master and {{cookiecutter.development_branch}}
          # histories in sync.
          MERGE_METHOD: merge
          # Use GitHub's default merge commit message.
          MERGE_COMMIT_MESSAGE: automatic
          # Never auto-merge from forks.
          # Forks SHOULD never cut PRs to master,
          # but check this just in case.
          MERGE_FORKS: false
